### ISSUE TITLE
Remove benches from ceremony lawn

### ISSUE THREAD

**Issue by tonygilkerson** [ohiobarn/flowerfarm#36]
Remove the benches from the ceremony lawn.  Stack them on the purgurla and the North end of the barn porch.  Avoid stacking taller than 5 benches tall

> Note: record this under `Wedding Help` on your timesheet

## What is needed

* no special requirements

## What to expect

* **How long will this take**: 30 min or less
* **How much coordination is needed**:  The first time we will do it together but after that no coordinations is needed 
* **Do we need to purchase supplies**: No

## Where

* [purgurla](https://www.google.com/maps/d/u/0/viewer?mid=1f8J60varqaHygKOHTuFFyNatDxRKZhm7&ll=39.85064410000001%2C-83.9824705&z=20)

**Comment by flowermama** [comment]
done
